### ISSUE TITLE
Compatible with model properties?

### ISSUE THREAD

**Issue by thumbtech** [joshhanley/sprucewire#4]
(Sorry to ask question here in issues ... perhaps points to issue with readme ...)

Given known limitations specified (treatment of collections), could sprucewire be recommended for use with bound model properties (an individual instance, e.g. `public Post $post;`), still preserving extra "goodness" such as Caleb's:

> Note: For this to work, you need to have a validation entry in the `$rules` property for any model attributes you want to bind to. Otherwise, an error will be thrown.

If not compatible, perhaps should be state explicitly in readme. Thank you!

**Comment by thumbtech** [comment]
Oops just noticed drop of Spruce for AlpineJS 3! Won't be leveraging therefore!

**Comment by joshhanley** [comment]
@thumbtech yeah it was compatible with individual instances, only collections where there are some issues.

But yeah Spruce doesn't support Alpine V3 due to the `$store` built into Alpine V3.
